
list1=["Bryan, G. L. (Columbia),",
"Norman, M. L. (UCSD), ",
"O\'Shea, B. W (Michigan State University),",
"Abel, T. (Stanford),",
"Wise, J. H. (Georgia Tech),",
"Turk, M. J. (Stanford), ",
"Reynolds, D. R. (Southern Methodist University),",
"Wang, P. (Nvidia), ",
"Skillman, S. W. (Stanford), ",
"Smith, B. (Michigan State University),",
"Harkness, R. P. (UCSD),",
"Bordner, J. (UCSD),",
"Kim, J. (UCSD),",
"Kuhlen, M. (UCB),",
"Xu, H. (UCSD),",
"Goldbaum, N. (UCSC),",
"Hummels, C. (University of Arizona),",
"Kritsuk, A. G. (UCSD),",
"Tasker, E. (Hokaido University), ",
"Skory, S. (Seagate),",
"Simpson, C. M. (Columbia),",
"Hahn, O., (ETH)",
"Oishi, J. S. (AMNH)",
"So, G. C. (UCSD),",
"Zhao, F.,",
"Cen, R. (Princeton),",
"Li, Y. (Columbia)",
"Nordlund, \AA (Neils Borh Institute),",
"Padoan, P. (University of Barcelona),",
#"Banerjee, R. (University of Hamburg),",
#"Federrath, C. (Monash University),",
#"Flock, M.,",
#"Lee, D. (Flash Center),",
#"Li, P. S. (UCB),",
#"M\\\"eller, W.-C. (MPIA),",
#"Teyssier, R. (ITP Zurich),",
#"Ustyugov, S. D. (Keyldish Institute),",
#"Vogel, C.,",
"Li, H. (LANL),",
"Li., S. (LANL),",
"Schmidt, W. (Univ Go\"ettingen),",
"Malinen, J. (Helsinki),",
"Juvela, M. (Helsinki),",
"Lunttila, T. (Helsinki),",
"Shetty, R. (Heidelburg),",
"Kauffmann, J. (CalTech),",
"Goodman, A.~A. (Harvard),",
"Rosolowsky, E.~W. (UBC),"
      ]

list1.sort()
for name in list1:
  print name, " ",
print "."
